# Generated by Django 4.2.28 on 2026-02-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS "testing" (
                    "id" bigserial PRIMARY KEY,
                    "test_case" varchar(255) NOT NULL,
                    "url" varchar(2048) NOT NULL,
                    "passed" boolean NOT NULL DEFAULT false,
                    "comment" text NOT NULL,
                    "created_at" timestamp with time zone NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "listing_data" (
                    "id" bigserial PRIMARY KEY,
                    "title" varchar(512) NOT NULL,
                    "price" varchar(100) NOT NULL DEFAULT '',
                    "image_url" varchar(2048) NOT NULL DEFAULT '',
                    "listing_url" varchar(2048) NOT NULL DEFAULT '',
                    "scraped_at" timestamp with time zone NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "suggestion_data" (
                    "id" bigserial PRIMARY KEY,
                    "text" varchar(512) NOT NULL,
                    "search_query" varchar(255) NOT NULL,
                    "captured_at" timestamp with time zone NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "network_logs" (
                    "id" bigserial PRIMARY KEY,
                    "url" varchar(2048) NOT NULL,
                    "method" varchar(10) NOT NULL DEFAULT 'GET',
                    "status_code" integer NULL,
                    "resource_type" varchar(50) NOT NULL DEFAULT '',
                    "captured_at" timestamp with time zone NOT NULL
                );
                CREATE TABLE IF NOT EXISTS "console_logs" (
                    "id" bigserial PRIMARY KEY,
                    "level" varchar(20) NOT NULL DEFAULT 'INFO',
                    "message" text NOT NULL,
                    "source" varchar(512) NOT NULL DEFAULT '',
                    "captured_at" timestamp with time zone NOT NULL
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name='consolelog',
            options={'verbose_name': 'Console Log', 'verbose_name_plural': 'Console Logs'},
        ),
        migrations.AlterModelOptions(
            name='listingdata',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='networklog',
            options={'verbose_name': 'Network Log', 'verbose_name_plural': 'Network Logs'},
        ),
        migrations.AlterModelOptions(
            name='suggestiondata',
            options={'verbose_name': 'Suggestion', 'verbose_name_plural': 'Suggestions'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "testing" DROP COLUMN IF EXISTS "created_at";',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='testresult',
                    name='created_at',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='consolelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consolelog',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='listingdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='networklog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10),
        ),
        migrations.AlterField(
            model_name='suggestiondata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
